sonar.projectKey=aceest-fitness
sonar.projectName=ACEest Fitness
sonar.projectVersion=3.2
sonar.sources=.
sonar.exclusions=**/tests/**,**/__pycache__/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=http://localhost:9000
sonar.login=YOUR_SONAR_TOKEN_HERE
