# BLUE = current stable version
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aceest-fitness
      version: blue
  template:
    metadata:
      labels:
        app: aceest-fitness
        version: blue
    spec:
      containers:
      - name: aceest
        image: sarikaupadhyay/aceest-fitness:v3.1
        ports:
        - containerPort: 5000
---
# GREEN = new version (deploy alongside blue)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aceest-fitness
      version: green
  template:
    metadata:
      labels:
        app: aceest-fitness
        version: green
    spec:
      containers:
      - name: aceest
        image: sarikaupadhyay/aceest-fitness:v3.2
        ports:
        - containerPort: 5000
---
# Service - switch 'version: blue' to 'version: green' to swap traffic
apiVersion: v1
kind: Service
metadata:
  name: aceest-service
spec:
  selector:
    app: aceest-fitness
    version: blue
  ports:
  - port: 80
    targetPort: 5000
  type: NodePort
